[package]
name = "passgen"
version = "0.1.0"
authors = ["Jeyachandran Rathnam <jai.rathnem@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
clap = "3.0.0-beta.2"
copypasta = "0.7.1"